spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/notice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true

  config:
    import:
      - classpath:/config/application-oauth.yml

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace